prSections:
  - title: kgt-ui
    filters: repo:kesko-dev/k-valikoima-gt-ui -author:@me
    limit: 50
  - title: kgt-ms
    filters: repo:kesko-dev/k-valikoima-gt-microservice -author:@me
    limit: 50
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Unread
    filters: is:unread involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 25
        hidden: false
      assignees:
        hidden: true
      reviewStatus:
      state:
      ci:
      lines:
        hidden: true
      base:
        width: 10
        hidden: false
  prsLimit: 100
  issuesLimit: 50
  preview:
    open: true # whether to have the preview pane open by default
    width: 80 # width in columns
  refetchIntervalMinutes: 20 # will refetch all sections every 30 minutes
repoPaths:
  :owner/:repo: ~/git/:owner/:repo # template if you always clone github repos in a consistent location
keybindings: # optional, define custom keybindings - see more info below
theme: # optional, see more info below
  ui:
    table:
      showSeparator: false
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#3E4057"
      warning: "#F23D5C"
      success: "#3DF294"
    background:
      selected: "#39386B"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
pager:
  diff: delta --side-by-side --line-numbers --hyperlinks --color-moved
confirmQuit: false
