#!/usr/bin/env zsh
pushd $DOTFILES
STOW_FOLDERS="zsh,tmux,bin,alacritty,gh-dash"

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
